  gitalk: true
  gitalk_clientID: '933ab0bb3e2464f51f27'
  gitalk_Secret: '67016febaae89221e9cbbad907d5f7a0c8e8b7da'
  gitalk_repo: 'cxk233.github.io'
  gitalk_owner: 'cxk233'
  gitalk_admin: 'cxk233'
  distractionFreeMode: true
